import { useEffect, useState } from 'react'
import { AdminSidebar } from '../../components/AdminSidebar'
import { getEvents, getRegistrations } from '../../lib/data'
import type { Event, Registration } from '../../types'

export default function Registrations() {
  const [regs, setRegs] = useState<Registration[]>([]); const [events, setEvents] = useState<Event[]>([]); const [query, setQuery] = useState(''); const [eventId, setEventId] = useState(''); const [message, setMessage] = useState('')
  useEffect(() => { getRegistrations().then(setRegs).catch(() => setMessage('Registrations require secure admin database access.')); getEvents().then(setEvents).catch(() => setMessage('Events could not be loaded.')) }, [])
  const shown = regs.filter(registration => (registration.name + registration.email + registration.college_email).toLowerCase().includes(query.toLowerCase()) && (!eventId || registration.event_id === eventId))
  const eventName = (registration: Registration) => registration.events?.title || events.find(event => event.id === registration.event_id)?.title || '—'
  return <div className="admin-layout"><AdminSidebar/><main className="admin-main"><p className="eyebrow">Participants</p><h1 style={{fontSize:'3rem',margin:'3px 0 24px',fontWeight:950}}>REGISTRATIONS</h1>{message&&<p role="status" style={{fontWeight:700}}>{message}</p>}<div className="registration-filters"><input className="field" placeholder="Search name or email" value={query} onChange={event => setQuery(event.target.value)}/><select className="field" value={eventId} onChange={event => setEventId(event.target.value)}><option value="">All events</option>{events.map(event => <option value={event.id} key={event.id}>{event.title}</option>)}</select></div><div className="registrations-table-desktop"><div className="table-wrap"><table className="table registrations-table"><thead><tr><th>Name</th><th>Personal email</th><th>College email</th><th>Phone</th><th>College</th><th>Year</th><th>Event</th><th>Registration date</th></tr></thead><tbody>{shown.map(registration => <tr key={registration.id}><td><b>{registration.name}</b></td><td>{registration.email}</td><td>{registration.college_email}</td><td>{registration.phone}</td><td>{registration.college}</td><td>{registration.year}</td><td>{eventName(registration)}</td><td>{new Date(registration.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></div><div className="registration-card-list">{shown.map(registration => <article className="admin-mobile-card" key={registration.id}><h2>{registration.name}</h2><dl><div><dt>Personal email</dt><dd>{registration.email}</dd></div><div><dt>College email</dt><dd>{registration.college_email}</dd></div><div><dt>Phone</dt><dd>{registration.phone}</dd></div><div><dt>College / Year</dt><dd>{registration.college} / {registration.year}</dd></div><div><dt>Event</dt><dd>{eventName(registration)}</dd></div><div><dt>Registration date</dt><dd>{new Date(registration.created_at).toLocaleDateString()}</dd></div></dl></article>)}</div>{!shown.length&&!message&&<p style={{fontWeight:700}}>No registrations found.</p>}</main></div>
}
